server:
  port: 8080
spring:
  application:
    name: sunny-cloud-system
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        server-addr: nacos.czy21-internal.com:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: sunny