server:
  port: 8080
spring:
  application:
    name: sunny-cloud-system
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      server-addr: nacos.ops.svc:8848
      config:
        namespace: sunny