server:
  port: 8080
spring:
  application:
    name: sunny-finance
  cloud:
    kubernetes:
      config:
        enabled: true
        sources:
          - name: sunny-finance
            namespace: stable
      reload:
        enabled: true
        mode: event
        strategy: refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always