server:
  port: 8080
spring:
  application:
    name: sunny-finance
---
spring:
  config:
    import: optional:configserver:http://spring-config.czy21-internal.com
    activate:
      on-profile: default