server:
  port: 8081
spring:
  config:
    import: optional:configserver:http://spring-config.czy21-internal.com
xxl-job:
  enabled: false
logging:
  level:
    com.sunny.system.core.mapper: debug

sunny:
  feign:
    product:
      url: 127.0.0.1:8082
#      url: http://sunny-cloud.czy21-internal.com/api/product/