server:
  port: 8081
spring:
  config:
    import: optional:configserver:http://spring-config.czy21-internal.com
  cloud:
    config:
      enabled: true
xxl-job:
  enabled: false
logging:
  level:
    com.sunny.system.core.mapper: debug