plugins {
    id 'com.sunny.framework.gradle' apply false
    id 'org.springframework.boot' apply false
}

group = 'com.sunny'
version = '1.0.0-SNAPSHOT'

def frontend_modules = [
        "sunny-admin",
        "sunny-auth-web",
        "sunny-product-web"
]

subprojects {
    if (project.name in frontend_modules) {

    } else {
        apply plugin: 'java-library'
        apply plugin: 'maven-publish'
        apply plugin: 'io.spring.dependency-management'
        apply plugin: "com.sunny.framework.common"
        apply plugin: "com.sunny.framework.lombok"

        if ("${name}".endsWith("-api")) {
            apply plugin: "com.sunny.framework.publish"
        }

        pluginManager.withPlugin("org.springframework.boot") {
            apply plugin: 'com.sunny.framework.spring.boot'
        }

        group = rootProject.group
        version = rootProject.version

        dependencyManagement {
            generatedPomCustomization {
                enabled = false
            }
            imports {
                mavenBom gradle.ext.development ? org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES : "com.sunny:sunny-framework-bom:${sunnyFrameworkVersion}"
            }
            dependencies {}
        }

        if (gradle.ext.development) {
            apply from: "${gradle.ext.sunnyFrameworkPath}/dependency.gradle"
        }

        dependencies {
            testImplementation "org.springframework.boot:spring-boot-starter-test"
            testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
        }
    }
}
