pluginManagement {
    plugins {
        id 'com.sunny.framework.gradle' version sunnyFrameworkVersion

        id 'org.springframework.boot' version springBootVersion
        id 'org.graalvm.buildtools.native' version '1.1.11'
        id "com.github.node-gradle.node" version "7.1.0"
    }
}

gradle.ext.development = providers.gradleProperty('development').map { it.toBoolean() }.orElse(false).get()
gradle.ext.sunnyFrameworkPath = file("../../sunny-framework/sunny-framework-java")

if (gradle.ext.development) {
    includeBuild("${gradle.ext.sunnyFrameworkPath}")
}

def includeModule(moduleName) {
    file("${moduleName}").list().findAll { file("${moduleName}/${it}/build.gradle").exists() }.each {
        include("${moduleName}:${it}")
    }
}

include 'sunny-admin'
include 'sunny-auth-web'
include 'sunny-product-web'

include 'sunny-gateway'

includeModule("sunny-example")
includeModule("sunny-auth")
includeModule("sunny-system")
includeModule("sunny-order")
includeModule("sunny-stock")
includeModule("sunny-product")
includeModule("sunny-finance")