server:
  port: 8081
spring:
  application:
    name: sunny-auth
  cloud:
    nacos:
      server-addr: nacos.czy21-internal.com:8848
      config:
        namespace: sunny

---
spring:
  config:
    import:
      - nacos:${spring.application.name}.yml
    activate:
      on-profile: default
logging:
  level:
    org.springframework.security: debug