server:
  port: 8081
spring:
  config:
    import:
      - nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        namespace: sunny
logging:
  level:
    com.sunny.system.core.mapper: debug