name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
      - uses: actions/setup-node@v4
        with: 
          node-version: '20.18.0'
      - name: Build framework
        working-directory: global/sunny-framework
        run: ./gradlew -I ${{ github.workspace }}/.github/init.gradle publishToMavenLocal
      - name: Build service
        working-directory: service
        run: npm_config_node_linker=hoisted ./gradlew -I ${{ github.workspace }}/.github/init.gradle build