server:
  port: 8082
spring:
  config:
    import:
      - nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        namespace: sunny
xxl-job:
  enabled: false

logging:
  level:
    org.jooq.tools.LoggerListener: debug
    org.springframework.jdbc: debug

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sunny:
  security:
    ignore-paths:
      - "/api/jooq/**"