server:
  port: 8082
spring:
  config:
    import:
      - nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        namespace: sunny
xxl-job:
  enabled: false
logging:
  level:
    com.sunny.system.core.mapper: debug
    org.jooq.tools.LoggerListener: debug
    org.springframework.jdbc: debug
sunny:
  security:
    ignore-paths:
      - "/api/jooq/**"